spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bootuser
    username: bootuser
    password: bootuser
---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

---

spring:
  thymeleaf:
    cache: false

---

spring:
  servlet.multipart:
    enabled: true
    location: /Users/jeongminji
    max-request-size: 30MB
    max-file-size: 10MB

---

logging:
  level:
    org.springframework.security.web: trace
    org.zerock: debug